version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(ci): "
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    reviewers:
      - "zyv"

  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(npm): "
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    reviewers:
      - "zyv"
